### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Atcold**
Better README.md with proper Markdown formatting

### CODE REVIEW

**Comment by dahu** [comment]
Thanks for the fixes. I switched from Markdown to Asciidoc in my github repos a while back. When I updated LearnVim's README recently, I*ass*umed it was in Asciidoc format and obviously didn't test the changes. :-/

**Comment by Atcold** [comment]
Oh :anguished: Why did you switched from *Markdown* to *Asciidoc*?

**Comment by dahu** [comment]
Asciidoc is much better than Markdown

I use  Asciidoc in all the doco places I can, including creating lecture
notes and slides. Github had very rudimentary Asciidoc support until
Asciidoctor. After that, I started switching over.

**Comment by Atcold** [comment]
Lecture notes?!?! Are you teaching? May I see an example?
How is AsciiDoc superior to Markdown?
Last thing, you said 'didn't test the changes. :-/'... Changes from?

**Comment by dahu** [comment]
A small sample of how I create lecture slides:
https://gist.github.com/dahu/9aad62389038c3967fe3

http://asciidoctor.org/docs/what-is-asciidoc/

I recently updated Learnvim's README prior to your edits, and when I made
those changes I assumed the document was in Asciidoc. I didn't generate a
local rendering to test my changes (make sure they looked right). I also
failed to check on github itself. Rushing.

**Comment by Atcold** [comment]
And you think that AsciiDoc is superior to Markdown? Why?

**Pull request merged**
